# Generated by Django 2.2.6 on 2019-10-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='No title', max_length=50)),
                ('foto', models.ImageField(upload_to='photos/')),
                ('pub_fecha', models.DateField(auto_now_add=True)),
                ('favorito', models.BooleanField(default=False)),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barber.Categoria')),
            ],
        ),
    ]
